In [1]:
print("Hello world")

Hello world


In [9]:
a = 1
b = 2

for i in range(b):
    print(i)

for i in range(4,-1,-2):
    print(i)

while i < 2:
    print(f"while loop {i}")
    i += 1

0
1
4
2
0
while loop 0
while loop 1


In [72]:
inp = input("type here something")
print(inp,type(inp))

q1 <class 'str'>


In [78]:
1/1.0, 1./1, 1+2/2*4

(1.0, 1.0, 5.0)

In [35]:
a = [1,2,[3,4]]
print(*a,sep = "\t")

print(a[0:2])
print(a[::-1])

1	2	[3, 4]
[1, 2]
[[3, 4], 2, 1]


In [21]:
test_list = ("", "GeeksforGeeks", "", "is", "best", "")
test_list[:1:-1]

('', 'best', 'is', '')

In [25]:
test_list[0] = 1

TypeError: 'tuple' object does not support item assignment

In [48]:
# %[flags][width][.precision]type
print("Geeks : %1d, Portal : %8.4f" % (1, 55.333))

print("Total students : %5d, Boys : %11d" % (240, 120))   # print integer value

print("%7.3o" % (25))   # print octal value

print("%10.3E" % (356.08977))   # print exponential value

Geeks : 1, Portal :  55.3330
Total students :   240, Boys :         120
    031
 3.561E+02


In [54]:
d1 = {1:'a',2:'b'}
print(d1.keys(),d1.values(),d1.items())

dict_keys([1, 2]) dict_values(['a', 'b']) dict_items([(1, 'a'), (2, 'b')])


In [63]:
for index,j in enumerate(d1.values()):
    print(index,j)

for i in d1.items():
    print(i)
d1[1] = 'aa'
d1[3] = 'habibi'
print(d1.items())

0 aa
1 b
2 habibi
(1, 'aa')
(2, 'b')
(3, 'habibi')
dict_items([(1, 'aa'), (2, 'b'), (3, 'habibi')])


In [81]:
s1 = {1,2,2,3}
s1.add('1')
print(s1)

user = 1
match user:
    case 1:
        print("Yes")
    case 2:
        print("No")
    case _:
        print(" None ")



{1, 2, 3, '1'}
Yes


In [88]:
# ternary operator
print(1 if True > False else 0) #
print(int(True),int(False))

# list comprehension
print([(i,i**3) for i in range(1,5) if i %2 == 0])



1
1 0
[(2, 8), (4, 64)]


In [90]:
# Positional
def func1(a, b):
    return a + b

result1 = func1(3, 4)  # 3 is assigned to a, and 4 is assigned to b

# Keyword
def func2(a, b):
    return a + b

result2 = func2(b=4, a=3)  # 3 is assigned to a, and 4 to b regardless of order

# Default
def func3(a, b=4):
    return a + b

result3 = func3(3)  # b defaults to 4, and 3 is assigned to a

# Variable length
def func4(*args):
    return sum(args)

result4 = func4(1, 2, 3, 4)  # args will be (1, 2, 3, 4)

# Variable Length keyword Arguments
# kwargs returns dict object with key = keyword and value = value
def func5(**kwargs):
    return kwargs

result5 = func5(a=1, b=2)  # kwargs will be {'a': 1, 'b': 2}

print(result1,result2,result3,result4,result5)

7 7 7 10 {'a': 1, 'b': 2}


In [95]:
def complex_function(a, b, /, c=2, *args, d, e=5, **kwargs):
    """
    Demonstrates the use of different types of function arguments in Python:
    - Positional-only arguments: a, b
    - Default argument: c
    - Variable-length positional arguments: *args
    - Keyword-only arguments: d, and optional e
    - Variable-length keyword arguments: **kwargs
    """
    print(f"Positional-only arguments: a = {a}, b = {b}")
    print(f"Default argument (c): {c}")
    print(f"Variable-length positional arguments (*args): {args}")
    print(f"Keyword-only arguments: d = {d}, e = {e}")
    print(f"Variable-length keyword arguments (**kwargs): {kwargs}")

    # Example calculation
    result = a + b + c + sum(args) + d + e + sum(kwargs.values())
    return result

# Example usage:
result = complex_function(1, 2, 4, 5,5,55, d=6, x=7, y=8)
print("Result of the function:", result)


Positional-only arguments: a = 1, b = 2
Default argument (c): 4
Variable-length positional arguments (*args): (5, 5, 55)
Keyword-only arguments: d = 6, e = 5
Variable-length keyword arguments (**kwargs): {'x': 7, 'y': 8}
Result of the function: 98


In [100]:
# nonlocal scope
def outer_function():
    x = "outer"

    def inner_function_1():
        x = "inner 1"

        def inner_function_2():
            nonlocal x
            x = "inner 2"

        inner_function_2()
        print("Value of x in inner_function_1:", x)

    inner_function_1()
    print("Value of x in outer_function:", x)

outer_function()

# Global Scope
def outer():
    global string
    string = "Favtutor"
    def inner():
        string= "Python Favtutor Classes" # Overwriting value of a variable string
        print("inner function:", string)

    inner()
    print("outer function:", string)

outer()

Value of x in inner_function_1: inner 2
Value of x in outer_function: outer
inner function: Python Favtutor Classes
outer function: Favtutor


In [98]:
# Closures
def outerFunction(text):

    def innerFunction():
        print(text)

    # Note we are returning function
    # WITHOUT parenthesis
    return innerFunction

if __name__ == '__main__':
    myFunction = outerFunction('Hey!')
    myFunction()

Hey!


In [102]:
# map, reduce, lambda

# map
numbers = (1, 2, 3, 4)
result = map(lambda x: x + x, numbers)
print(list(result))

def addition(n):
    return n + n

# We double all numbers using map()
result = map(addition, numbers)
print(list(result))

[2, 4, 6, 8]
[2, 4, 6, 8]


In [109]:
# Filter
def fun(variable):
    letters = {'a', 'e', 'i', 'o', 'u'}
    if variable in letters:
        return True
    else:
        return False


# sequence
sequence = ['g', 'e', 'e', 'j', 'k', 's', 'p', 'r']

# using filter function
filtered = filter(fun, sequence)

print('The filtered letters are:')
for s in filtered:
    print(s)

# a list contains both even and odd numbers.
seq = [0, 1, 2, 3, 5, 8, 13]

# result contains odd numbers of the list
result = filter(lambda x: x % 2 != 0, seq)
print("Odd list",list(result))

# result contains even numbers of the list
result = filter(lambda x: x % 2 == 0, seq)
print("Even list",list(result))

The filtered letters are:
e
e
Odd list [1, 3, 5, 13]
Even list [0, 2, 8]


In [113]:
# Reduce
# importing functools for reduce()
import functools


# initializing list
lis = [1, 3, 5, 6, 2]

def sum1(*args):
    return sum([lis[i] for i in range(len(lis)) if i % 2 == 0])
# using reduce to compute sum of list
print("The sum of the even indexed list elements is : ", end="")
print(functools.reduce(sum1, lis))

# using reduce to compute maximum element from list
print("The maximum element of the list is : ", end="")
print(functools.reduce(lambda a, b: a if a > b else b, lis))

The sum of the even indexed list elements is : 8
The maximum element of the list is : 6


In [114]:
# Classes
class Dog:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def bark(self):
        return f"{self.name} barks!"

# Creating an object of Dog class
buddy = Dog("Buddy", 3)
print(buddy.bark())  # Outputs: Buddy barks!


Buddy barks!


In [3]:
# Inheritance
class Animal:
    def __init__(self, name):
        self._name = name

    # Method abstraction in base class
    def speak(self):
        raise NotImplementedError("Subclasses must implement this method")

class Cat(Animal):
    def speak(self):
        return f"{self._name} says Meow"

# Using the inherited class
whiskers = Cat("Whiskers")

print(whiskers._name,whiskers.speak())  # Outputs: Whiskers says Meow

Whiskers Whiskers says Meow


In [128]:
# Python program invoking a
# method using super()
from abc import ABC

class R(ABC):
    def rk(self):
        print("Abstract Base Class")

class K(R):
    def rk(self):
        super().rk()
        print("subclass ")

# Driver code
r = K()
r.rk()

Abstract Base Class
subclass 


In [117]:
# Encapsulation
class Computer:
    def __init__(self):
        self.__max_price = 900

    def sell(self):
        return f"Selling Price: {self.__max_price}"

    def set_max_price(self, price):
        self.__max_price = price

c = Computer()
print(c.sell())  # Selling Price: 900

c.__max_price = 1000  # Won't change the price because it's encapsulated
print(c.sell())  # Selling Price: 900

c.set_max_price(1000)
print(c.sell())


Selling Price: 900
Selling Price: 900
Selling Price: 1000


In [118]:
# Polymorphism
class Bird:
    def intro(self):
        return "There are many types of birds."

    def flight(self):
        return "Most of the birds can fly but some cannot."

class Sparrow(Bird):
    def flight(self):
        return "Sparrows can fly."

class Ostrich(Bird):
    def flight(self):
        return "Ostriches cannot fly."

# Polymorphic use
bird_list = [Bird(), Sparrow(), Ostrich()]
for bird in bird_list:
    print(bird.intro(), bird.flight())


There are many types of birds. Most of the birds can fly but some cannot.
There are many types of birds. Sparrows can fly.
There are many types of birds. Ostriches cannot fly.


In [15]:
for i in range(47,127):
    print(chr(i), end = " ")

/ 0 1 2 3 4 5 6 7 8 9 : ; < = > ? @ A B C D E F G H I J K L M N O P Q R S T U V W X Y Z [ \ ] ^ _ ` a b c d e f g h i j k l m n o p q r s t u v w x y z { | } ~ 
 49


In [129]:
A = {0, 2, 4, 6, 8};
B = {1, 2, 3, 4, 5};

print( A ^ B)

{0, 1, 3, 5, 6, 8}


In [130]:
str='qwertyuiop'
str[2] ='0'

TypeError: 'str' object does not support item assignment

### NumPy Tutorials


In [131]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [17]:
import numpy as np

np.array([1,2,3])

array([1, 2, 3])

In [18]:
a = np.arange(16.0).reshape(4, 2, 2)

print(a.shape,a.ndim,a.itemsize,a.dtype)
print(a)

(4, 2, 2) 3 8 float64
[[[ 0.  1.]
  [ 2.  3.]]

 [[ 4.  5.]
  [ 6.  7.]]

 [[ 8.  9.]
  [10. 11.]]

 [[12. 13.]
  [14. 15.]]]


In [19]:
np.zeros((3, 4),dtype = np.int16), np.ones((2, 3, 4), dtype=np.int16), np.empty((2, 3))

(array([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=int16),
 array([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],
 
        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]], dtype=int16),
 array([[-1.42656443e-311, -2.12359768e+263,  1.42656856e-311],
        [ 1.42656856e-311,  8.89318163e-323,  1.97626258e-323]]))

In [20]:
np.arange(10, 30, 5), np.arange(0, 2, 0.3), np.arange(10)**3 # it accepts float arguments


(array([10, 15, 20, 25]),
 array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8]),
 array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32))

In [21]:
print(a)
a[2:4,1,0], a[2:4,0,1],


[[[ 0.  1.]
  [ 2.  3.]]

 [[ 4.  5.]
  [ 6.  7.]]

 [[ 8.  9.]
  [10. 11.]]

 [[12. 13.]
  [14. 15.]]]


(array([10., 14.]), array([ 9., 13.]))

In [22]:
from numpy import pi
np.linspace(9, 10, 4)


array([ 9.        ,  9.33333333,  9.66666667, 10.        ])

In [23]:
print(a.ravel()) # Gives a view of flattened list
print(a.flatten()) # Gives copy of flattened list

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [178]:
a.reshape(4,-1)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [214]:
random_generator = np.random.default_rng()
a = np.floor(10 * random_generator.random((2, 2,2)))
print(a,b)
b = np.floor(10 * random_generator.random((2, 2,2)))
np.vstack((a,b)),np.hstack((a,b))

[[[7. 5.]
  [1. 3.]]

 [[1. 6.]
  [4. 2.]]] [[1. 8.]
 [8. 4.]]


(array([[[7., 5.],
         [1., 3.]],
 
        [[1., 6.],
         [4., 2.]],
 
        [[2., 1.],
         [9., 2.]],
 
        [[9., 8.],
         [5., 3.]]]),
 array([[[7., 5.],
         [1., 3.],
         [2., 1.],
         [9., 2.]],
 
        [[1., 6.],
         [4., 2.],
         [9., 8.],
         [5., 3.]]]))

In [206]:
a.resize(4,4)

For arrays with more than two dimensions,  
- hstack stacks along their second axes,  
- vstack stacks along their first axes, and 
- Concatenate allows for an optional arguments giving the number of the axis along which the concatenation should happen.

In [215]:
np.info(np.insert)

Insert values along the given axis before the given indices.

Parameters
----------
arr : array_like
    Input array.
obj : int, slice or sequence of ints
    Object that defines the index or indices before which `values` is
    inserted.

    .. versionadded:: 1.8.0

    Support for multiple insertions when `obj` is a single scalar or a
    sequence with one element (similar to calling insert multiple
    times).
values : array_like
    Values to insert into `arr`. If the type of `values` is different
    from that of `arr`, `values` is converted to the type of `arr`.
    `values` should be shaped so that ``arr[...,obj,...] = values``
    is legal.
axis : int, optional
    Axis along which to insert `values`.  If `axis` is None then `arr`
    is flattened first.

Returns
-------
out : ndarray
    A copy of `arr` with `values` inserted.  Note that `insert`
    does not occur in-place: a new array is returned. If
    `axis` is None, `out` is a flattened array.

See Also
--------
append 

In [4]:

def combinationSum(nums, target):
    ans = []
    out = []

    def backtrack(inp,out,sum_out):
        print(inp,out,sum_out)
        if sum_out == target:
            ans.append(out[:])
            return

        if target < sum_out:
            print("yay",inp,out,sum_out,target)
            return

        if nums[inp] + sum_out <= target:
            print(inp,out,sum_out)
            out.append(nums[inp])
            backtrack(inp,out,sum_out + nums[inp])
            out.pop()

        backtrack(inp + 1,out,sum_out)

    backtrack(0,out,0)
    return ans

nums = [2,2,5]
target = 9
combinationSum(nums,target)

0 [] 0
0 [] 0
0 [2] 2
0 [2] 2
0 [2, 2] 4
0 [2, 2] 4
0 [2, 2, 2] 6
0 [2, 2, 2] 6
0 [2, 2, 2, 2] 8
1 [2, 2, 2, 2] 8
2 [2, 2, 2, 2] 8
3 [2, 2, 2, 2] 8


IndexError: list index out of range

In [5]:
3 * 'i'

'iii'

In [6]:
len(str(1111))

4

In [13]:

def numTeams(rating) -> int:
    ans = 0
    def backtrack(ip,op,team_len,incr_decr):
        nonlocal ans
        if team_len == 3:
            ans += 1
            return
        if ip == len(rating) or len(rating) - op < 2:
            return

        if op == -1 or (incr_decr == 1 and rating[ip] > rating[op]) or (incr_decr == 0 and rating[ip] < rating[op]):
            backtrack(ip + 1, ip, team_len + 1, incr_decr)

        backtrack(ip + 1, op, team_len, incr_decr)

        return

    backtrack(0,-1,0,1)
    backtrack(0,-1,0,0)

    return ans


In [15]:
rating = [1414,158,710,2814,965,585,620,52,2327,2390,2018,486,1166,2997,2715,336,2143,283,2705,467,381,2463,3000,703,1096,265,130,100,2194,2484,2501,1673,65,2447,663,2136,2039,2683,2093,2504,495,805,2712,512,85,1353,1520,2189,1274,1038,1829,2235,2127,2422,1569,731,469,2602,946,345,2292,2805,1579,1384,2040,921,1677,1074,814,1243,1537,2993,2596,1557,2034,2719,1185,80,1872,842,1546,1430,1212,2284,12,629,617,1661,1442,2356,1067,2632,753,1774,1848,916,728,1818,841,2804,779,280,2436,1519,1440,2291,760,2205,276,2057,563,822,707,2112,2701,113,263,164,2027,478,1705,1494,2208,1897,2352,2773,866,2725,645,1088,1361,48,2643,369,2038,2398,801,373,485,2916,2963,2467,2713,54,2396,1270,1322,2151,1046,1469,2965,1313,2191,1623,340,1299,714,851,797,2584,1016,649,2800,2911,894,930,2366,1948,2351,2223,1835,67,2512,51,1992,1903,1041,604,2401,943,2991,2367,1699,2097,671,1535,1856,1688,194,2454,2689,2718,2013,1665,2437,1823,242,719,1861,2329,2486,150,1454,2594,2192,2044,742,1629,1931,1127,64,2244,389,1698,2354,1639,2954,2700,1967,97,2174,2679,812,2024,2574,1175,1246,1236,647,1759,844,2005,35,195,1493,43,197,2310,2830,2193,2369,1044,406,1898,2211,1630,745,1297,665,2710,2442,2889,1521,2263,2011,2798,1189,2985,231,1102,2145,941,162,2478,1982,1601,1421,1918,2631,944,1220,1859,2690,219,1398,1604,1183,2121,2086,1068,1251,2111,2020,143,2844,198,1717,2957,2595,2381,1985,2851,2061,1385,1156,696,545,1203,901,1502,254,2187,1367,28,2818,1037,517,2677,134,2854,2423,1,298,2389,2008,2842,1868,302,2152,1562,754,2903,1561,1470,1943,1076,987,1578,2949,1081,2458,608,1882,1485,896,1410,2582,669,256,1913,2046,1965,272,170,1807,2471,1885,1153,1907,331,1524,989,2344,243,1177,2202,1712,1953,1054,1625,1827,2550,112,1459,1226,751,556,1933,1810,2681,2990,1465,631,2958,2824,1248,2864,1254,222,1732,501,2470,2156,687,2765,1260,2311,133,2651,1452,2334,878,2479,1125,746,23,258,1637,2142,1308,2502,1210,686,141,1990,2457,1301,2987,834,2675,1196,2264,1761,2625,2953,1422,729,1293,1172,2489,1233,1239,2724,127,2544,632,1805,2146,422,1143,2951,2564,252,2912,2350,981,1007,1373,1619,2132,172,268,1105,2138,2802,1173,300,1002,664,1320,997,1517,1352,882,2739,2728,2338,1436,446,1492,506,2559,1201,885,1111,1813,514,2424,2070,1039,59,2047,1199,2275,838,1026,1427,2259,2845,717,701,2197,1224,2462,2518,781,1668,2960,1141,1434,1008,2726,1850,1873,1779,2736,764,2238,399,2714,1735,2716,317,1832,1245,228,1474,2838,641,1020,934,2359,239,318,361,2167,1342,2721,798,2532,312,794,2393,782,1473,2915,2979,2343,802,1996,1478,1471,1816,2861,609,1193,1680,2934,2707,2590,858,1666,2099,2410,2857,156,2273,108,672,771,1504,2196,1244,677,2812,1523,534,1169,2461,658,1392,2052,1029,2466,2368,1278,2576,2200,2629,2468,1917,2823,2939,2134,642,2117,1476,1881,2460,484,261,275,1508,2503,2150,1643,2472,2165,1325,1501,1785,790,1375,1180,383,2959,2270,223,1290,148,324,1294,536,2362,2699,1603,2131,567,2635,1505]

numTeams(rating)

12670965

In [27]:
nums = [1,1,1]
k = 2
l,r = 0,0
n = len(nums)
ans = 0
curr_sum = 0
while r < n:
    # print(l,r)
    curr_sum += nums[r]
    if curr_sum < k:
        r += 1
    elif curr_sum == k:
        print(l,r, curr_sum)
        ans += 1
        curr_sum -= nums[l]
        l += 1
    else:
        while l < r and curr_sum > k:
            curr_sum -= nums[l]
            l += 1

print(ans)



0 1 2
1 1 2
2 1 2
3 1 2


IndexError: list index out of range

In [28]:
coins = [411,412,413,414,415,416,417,418,419,420,421,422]
amount = 9864

dp = [[amount + 1 for _ in range(amount + 1)] for _ in range(len(coins) + 1)]

for i in range(len(coins)):
    dp[i][0] = 0

def backtrack(ip, amt):
    if dp[ip][amt] != amount + 1:
        return dp[ip][amt]

    # if amt == 0:
    #     return 0
    if ip < 0:
        return amount + 1

    if coins[ip - 1] <= amt:
        dp[ip][amt] = min(backtrack(ip - 1, amt), 1 + backtrack(ip, amt - coins[ip - 1]))
    else:
        dp[ip][amt] = backtrack(ip - 1, amt)

    return dp[ip][amt]

result = backtrack(len(coins), amount)
print(result)


KeyboardInterrupt: 

In [30]:
def numberOfDays(weights, capacity):
    cum_weight = 0
    days = 0
    for w in weights:
        cum_weight += w
        if cum_weight > capacity:
            days += 1
            cum_weight = w
    if cum_weight > 0:
        days += 1
    return days

weights = [1,2,3,1,1]
capacity = 3
numberOfDays(weights, capacity)

3

In [15]:
import sys
import math

# structure of a node of binary tree
class Node:
    def __init__(self,data):
        self.val = data
        self.left = None
        self.right = None

# Helper function that allocates a new node with the
#given data and NULL left and right pointers.
def getNode(data):
        return Node(data)

def getPath(root, path, target):
     if not root:
          return False
     if root.val == target:
          return path
     path.append(root.val)
     left = getPath(root.left, path, target)
     if left:
          return left
     right = getPath(root.right, path, target)
     if right:
          return right
     path.pop()
     return False

def printPaths(path1, path2):
     flag = False
     if len(path1) > len(path2):
          path1, path2 = path2, path1
          flag = True
     n1 = len(path1)
     n2 = len(path2)

     j = 0
     k = 0
     while j < n1 and j < n2:
          if path1[j] != path2[j]:
               k = j - 1
               break
          else:
               j += 1

     return path1[k:][::-1] + path2[k + 1:] if not flag else path2[k:][::-1] + path1[k + 1:]
if __name__=='__main__':

    # binary tree formation
    root = getNode(0)
    root.left = getNode(1)
    root.left.left = getNode(3)
    root.left.left.left = getNode(7)
    root.left.right = getNode(4)
    root.left.right.left = getNode(8)
    root.left.right.right = getNode(9)
    root.right = getNode(2)
    root.right.left = getNode(5)
    root.right.right = getNode(6)
    node1=7
    node2=5
    path1 = getPath(root,[],node1)
    path1.append(node1)
    path2 = getPath(root,[], node2)
    path2.append(node2)
    print(path1, path2)
    print(printPaths(path1, path2))


[0, 1, 3, 7] [0, 2, 5]
[7, 3, 1, 0, 2, 5]


In [6]:
from collections import deque
class Solution:
    def wallsAndGates(self, rooms) -> None:
        """
        Do not return anything, modify rooms in-place instead.
        """
        r,c = len(rooms), len(rooms[0])
        k = 2 ** 31 - 1
        que = deque()

        for i in range(r):
            for j in range(c):
                if rooms[i][j] == 0:
                    que.append((i, j))

        directions = [(1,0),(-1,0),(0,1),(0,-1),]
        while que:
            i, j = que.popleft()
            for direction in directions:
                x, y = i + direction[0], j + direction[1]
                if x < 0 or x >= r or y < 0 or y >= c or rooms[x][y] != k:
                    continue

                rooms[x][y] = rooms[i][j] + 1
                que.append((x, y))

board = [[0,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647],
         [2147483647,0,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647],
         [2147483647,2147483647,0,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647],[2147483647,2147483647,2147483647,0,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647],[2147483647,2147483647,2147483647,2147483647,0,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647],[2147483647,2147483647,2147483647,2147483647,2147483647,0,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647],[2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,0,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647],[2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,0,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647],[2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,0,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647],[2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,0,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647],[2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,0,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647],[2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,0,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647],[2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,0,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647],[2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,0,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647],[2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,0,2147483647,2147483647,2147483647,2147483647,2147483647],[2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,0,2147483647,2147483647,2147483647,2147483647],[2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,0,2147483647,2147483647,2147483647],[2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,0,2147483647,2147483647],[2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,0,2147483647],[2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,0]]

a = Solution().wallsAndGates(board)
print(board)


[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19], [1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18], [2, 1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17], [3, 2, 1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], [4, 3, 2, 1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], [5, 4, 3, 2, 1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14], [6, 5, 4, 3, 2, 1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], [7, 6, 5, 4, 3, 2, 1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], [8, 7, 6, 5, 4, 3, 2, 1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], [9, 8, 7, 6, 5, 4, 3, 2, 1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0, 1, 2, 3, 4, 5, 6, 7, 8], [12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0, 1, 2, 3, 4, 5, 6, 7], [13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0, 1, 2, 3, 4, 5, 6], [14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0, 1, 2, 3, 4, 5],

In [7]:
b = [[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19],[1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18],[2,1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17],[3,2,1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],[4,3,2,1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],[5,4,3,2,1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14],[6,5,4,3,2,1,0,1,2,3,4,5,6,7,8,9,10,11,12,13],[7,6,5,4,3,2,1,0,1,2,3,4,5,6,7,8,9,10,11,12],[8,7,6,5,4,3,2,1,0,1,2,3,4,5,6,7,8,9,10,11],[9,8,7,6,5,4,3,2,1,0,1,2,3,4,5,6,7,8,9,10],[10,9,8,7,6,5,4,3,2,1,0,1,2,3,4,5,6,7,8,9],[11,10,9,8,7,6,5,4,3,2,1,0,1,2,3,4,5,6,7,8],[12,11,10,9,8,7,6,5,4,3,2,1,0,1,2,3,4,5,6,7],[13,12,11,10,9,8,7,6,5,4,3,2,1,0,1,2,3,4,5,6],[14,13,12,11,10,9,8,7,6,5,4,3,2,1,0,1,2,3,4,5],[15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0,1,2,3,4],[16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0,1,2,3],[17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0,1,2],[18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0,1],[19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0]]
print(board == b)

True


In [4]:
class UnionSet:
    def __init__(self, val):
        self.parent = self  # Initially, a node is its own parent
        self.rank = 0

    def findParent(self, node):
        if node.parent != node:
            node.parent = self.findParent(node.parent)  # Path compression
        return node.parent

    def union(self, node1, node2):
        n1 = self.findParent(node1)
        n2 = self.findParent(node2)
        if n1 == n2:
            return False
        self.link(n1, n2)
        return True

    def link(self, node1, node2):
        if node1.rank > node2.rank:
            node2.parent = node1
        else:
            node1.parent = node2
            if node1.rank == node2.rank:
                node2.rank += 1

# Example usage
nodeA = UnionSet('A')
nodeB = UnionSet('B')
nodeC = UnionSet('C')
node = UnionSet('A')
# Union operations
nodeA.union(nodeA, nodeB)  # Union A and B
nodeA.union(nodeB, nodeC)  # Union B and C
nodeA.union(node, nodeC)
nodeA.union(node, nodeC)
print(nodeA)

In [20]:
def findMaximumQuality(packets, channels):
    packets.sort()
    n = len(packets)
    if n == channels:
        return sum(packets)

    dp = [[0 for j in range(n + 1)] for i in range(channels + 1)]

    for i in range(n):
        if  i % 2 == 0:
            dp[1][i + 1] = packets[i//2]
        else:
            dp[1][i + 1] = (packets[i//2] + packets[(i//2) + 1])/2

    for i in range(2, channels + 1):
        for j in range(i, n + 1):
            dp[i][j] = dp[i-1][j-1] + packets[j - 1]
    print(dp)
    # TC O(nc + n log n)),  SC O(nc)
    return dp[channels][n]

packets = [1,2,5,4,3]
channels = 3
findMaximumQuality(packets, channels)


[[0, 0, 0, 0, 0, 0], [0, 1, 1.5, 2, 2.5, 3], [0, 0, 3, 4.5, 6, 7.5], [0, 0, 0, 6, 8.5, 11]]


11

In [62]:
def getMaxConsecutiveON(server_states: str, k: int) -> int:

    n = len(server_states)
    if n <= k:
        return n

    index = [0]
    for i in range(1, n):
        if server_states[i] != server_states[i - 1]:
            index.append(i)
    index.append(n)

    l = 0
    window = 0
    ans = 0
    for r in range(len(index)- 1):
        if server_states[index[r]] == '0':
            window += 1
        while window > k:
            if server_states[index[l]] == '0':
                window -= 1
            l += 1
        ans = max(ans, index[r + 1] - index[l])
    return ans

server_states, k = "00010", 1 # "11101010110011", 1
getMaxConsecutiveON(server_states, k)



4

In [1]:
def DFS_recursive_disconnected(graph):
    def DFS_recursive(node, visited):
        visited.add(node)
        print(node)  # or process the node in some way
        
        for neighbor in graph[node]:
            if neighbor not in visited:
                DFS_recursive(neighbor, visited)
    
    visited = set()
    
    for node in graph:
        if node not in visited:
            DFS_recursive(node, visited)

# Example usage
graph = {
    1: [],
    2: [3, 4, 1],
    3: [],
    4: [],
    5: [4]
}

DFS_recursive_disconnected(graph)


1
2
3
4
5


In [3]:
def kosaraju_scc(graph):
    def dfs(node, visited, stack):
        visited.add(node)
        for neighbor in graph[node]:
            if neighbor not in visited:
                dfs(neighbor, visited, stack)
        stack.append(node)

    def dfs_transposed(node, visited, transposed_graph):
        visited.add(node)
        for neighbor in transposed_graph[node]:
            if neighbor not in visited:
                dfs_transposed(neighbor, visited, transposed_graph)

    # Step 1: Perform DFS on the original graph to get the finish times
    visited = set()
    stack = []
    for node in graph:
        if node not in visited:
            dfs(node, visited, stack)

    # Step 2: Transpose the graph
    transposed_graph = {node: [] for node in graph}
    for node in graph:
        for neighbor in graph[node]:
            transposed_graph[neighbor].append(node)

    # Step 3: Perform DFS on the transposed graph in the order of decreasing finish times
    visited.clear()
    scc_count = 0
    while stack:
        node = stack.pop()
        if node not in visited:
            dfs_transposed(node, visited, transposed_graph)
            scc_count += 1

    return scc_count

# Example usage
graph = {
    1: [],
    2: [3, 4, 1],
    3: [],
    4: [],
    5: [4]
}

print("Number of strongly connected components:", kosaraju_scc(graph))


Number of strongly connected components: 5


In [ ]:
from PyPDF2 import PdfReader
import pandas as pd

# Path to your PDF file
pdf_path = r"C:\Users\sasan\Downloads\dharani master\dharani master\DHARANIpage8.pdf"

pdf_reader = PdfReader(pdf_path)

# Extract text from the first page
page = pdf_reader.pages[0]
text = page.extract_text()

print(text)
# Splitting the extracted text into lines
lines = text.split('\n')

# Defining a structure for the data
columns = ["Loan Account No.", "Pattadar Passbook No.", "Pattadar Name", "Father / Husband's Name", "Survey No./Sub-Division No.", "Extent (Ac.Gts)", "Type of Loan", "Type of Charge", "Loan Amount (in INR)"]
data = []

# Process each line to populate the DataFrame
for line in lines:
    # Adjust splitting logic as necessary based on your specific PDF content
    row = line.split()
    if len(row) == 9:  # Check if the row has the expected number of columns
        data.append(row)

print(data)
# Create a DataFrame
df = pd.DataFrame(data, columns=columns)

# Save the DataFrame to Excel
excel_path = "output.xlsx"
df.to_excel(excel_path, index=False)

In [1]:
class MenuItem:
    def __init__(self, name, price):
        self.name = name
        self.price = price

class Bill:
    def __init__(self, table_number, server_name):
        self.table_number = table_number
        self.server_name = server_name
        self.items = []
        self.gst_rate = 0.125

    def add_item(self, item):
        self.items.append(item)

    def calculate_total(self):
        subtotal = sum(item.price for item in self.items)
        gst = subtotal * self.gst_rate
        total = subtotal
        return subtotal, gst, total

    def print_bill(self):
        print(f"Table Number: {self.table_number}")
        print(f"Server: {self.server_name}")
        print("Items:")
        for item in self.items:
            print(f" - {item.name}: ${item.price:.2f}")
        subtotal, gst, total = self.calculate_total()
        print(f"Subtotal: ${subtotal:.2f}")
        print(f"GST (12.5%): ${gst:.2f}")
        print(f"Total: ${total:.2f}")

class Restaurant:
    def __init__(self):
        self.menu = []
        self.bills = []

    def add_menu_item(self, name, price):
        self.menu.append(MenuItem(name, price))

    def create_bill(self, table_number, server_name):
        bill = Bill(table_number, server_name)
        self.bills.append(bill)
        return bill

    def split_bill(self, bill, num_splits):
        split_bills = []
        for _ in range(num_splits):
            split_bills.append(Bill(bill.table_number, bill.server_name))
        for item in bill.items:
            for split_bill in split_bills:
                split_bill.add_item(item)
        return split_bills

# Example usage
restaurant = Restaurant()
restaurant.add_menu_item("Pasta", 12.00)
restaurant.add_menu_item("Pizza", 15.00)
restaurant.add_menu_item("Salad", 8.00)

# Create a bill for table 1
bill = restaurant.create_bill(1, "John")

# Add items to the bill
bill.add_item(restaurant.menu[0])  # Pasta
bill.add_item(restaurant.menu[1])  # Pizza

# Print the bill
bill.print_bill()

# Split the bill into 2
split_bills = restaurant.split_bill(bill, 2)
for i, split_bill in enumerate(split_bills, 1):
    print(f"\nSplit Bill {i}:")
    split_bill.print_bill()

Table Number: 1
Server: John
Items:
 - Pasta: $12.00
 - Pizza: $15.00
Subtotal: $27.00
GST (12.5%): $3.38
Total: $27.00

Split Bill 1:
Table Number: 1
Server: John
Items:
 - Pasta: $12.00
 - Pizza: $15.00
Subtotal: $27.00
GST (12.5%): $3.38
Total: $27.00

Split Bill 2:
Table Number: 1
Server: John
Items:
 - Pasta: $12.00
 - Pizza: $15.00
Subtotal: $27.00
GST (12.5%): $3.38
Total: $27.00


In [2]:
class MenuItem:
    def __init__(self, name, price):
        self.name = name
        self.price = price

class Bill:
    def __init__(self, table_number, server_name):
        self.table_number = table_number
        self.server_name = server_name
        self.items = []
        self.gst_rate = 0.125

    def add_item(self, item):
        self.items.append(item)

    def calculate_total(self):
        subtotal = sum(item.price for item in self.items)
        gst = subtotal * self.gst_rate
        total = subtotal + gst
        return subtotal, gst, total

    def print_bill(self):
        print(f"Table Number: {self.table_number}")
        print(f"Server: {self.server_name}")
        print("Items:")
        for item in self.items:
            print(f" - {item.name}: ${item.price:.2f}")
        subtotal, gst, total = self.calculate_total()
        print(f"Subtotal: ${subtotal:.2f}")
        print(f"GST (12.5%): ${gst:.2f}")
        print(f"Total: ${total:.2f}")

class Restaurant:
    def __init__(self):
        self.menu = []
        self.bills = []

    def add_menu_item(self, name, price):
        self.menu.append(MenuItem(name, price))

    def create_bill(self, table_number, server_name):
        bill = Bill(table_number, server_name)
        self.bills.append(bill)
        return bill

    def split_bill(self, bill, num_splits):
        split_bills = [Bill(bill.table_number, bill.server_name) for _ in range(num_splits)]
        for item in bill.items:
            split_price = item.price / num_splits
            for split_bill in split_bills:
                split_bill.add_item(MenuItem(item.name, split_price))
        
        return split_bills

# Example usage
restaurant = Restaurant()
restaurant.add_menu_item("Pasta", 12.00)
restaurant.add_menu_item("Pizza", 15.00)
restaurant.add_menu_item("Salad", 8.00)

# Create a bill for table 1
bill = restaurant.create_bill(1, "Alice")
bill.add_item(restaurant.menu[0])  # Pasta
bill.add_item(restaurant.menu[1])  # Pizza

# Print the bill
bill.print_bill()

# Split the bill into 2
split_bills = restaurant.split_bill(bill, 2)
for i, split_bill in enumerate(split_bills, start=1):
    print(f"\nSplit Bill {i}:")
    split_bill.print_bill()

Table Number: 1
Server: Alice
Items:
 - Pasta: $12.00
 - Pizza: $15.00
Subtotal: $27.00
GST (12.5%): $3.38
Total: $30.38

Split Bill 1:
Table Number: 1
Server: Alice
Items:
 - Pasta: $6.00
 - Pizza: $7.50
Subtotal: $13.50
GST (12.5%): $1.69
Total: $15.19

Split Bill 2:
Table Number: 1
Server: Alice
Items:
 - Pasta: $6.00
 - Pizza: $7.50
Subtotal: $13.50
GST (12.5%): $1.69
Total: $15.19


In [3]:
def print_spiral(matrix):
    if not matrix or not matrix[0]:
        return

    top, bottom = 0, len(matrix) - 1
    left, right = 0, len(matrix[0]) - 1

    while top <= bottom and left <= right:
        # Print the top row
        for i in range(left, right + 1):
            print(matrix[top][i], end=" ")
        top += 1

        # Print the right column
        for i in range(top, bottom + 1):
            print(matrix[i][right], end=" ")
        right -= 1

        if top <= bottom:
            # Print the bottom row
            for i in range(right, left - 1, -1):
                print(matrix[bottom][i], end=" ")
            bottom -= 1

        if left <= right:
            # Print the left column
            for i in range(bottom, top - 1, -1):
                print(matrix[i][left], end=" ")
            left += 1

# Example usage:
matrix = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
]

print_spiral(matrix)

1 2 3 4 8 12 16 15 14 13 9 5 6 7 11 10 

In [4]:
def reversePairs(self, nums: List[int]) -> int:
    ans = [0]

    def merge(l, mid, r):
        print("merge",l, mid, r)
        i, j = 0, 0
        arr = []
        while i <= mid and j <= r:
            print(i, j)
            if nums[i] > nums[j]:
                arr.append(nums[j])
                j += 1
            else:
                arr.append(nums[i])
                i += 1
        
        while i <= mid:
            arr.append(nums[i])
            i += 1                

        while j <= r:
            arr.append(nums[j])
            i += 1  

        for i in range(l, mid + 1):
            nums[i] = arr[l - i]
        
        return
    def countPairs(l, mid, r):
        j = mid + 1
        cnt = 0
        for i in range(l, mid + 1):
            while j < r and nums[i] > 2 * nums[j]:
                j += 1
            
            cnt += j - mid - 1
        return cnt

    def mergeSort(l, r):
        if l == r:
            return
        mid = l + (r - l) // 2
        mergeSort(l, mid)
        mergeSort(mid + 1, r)
        ans[0] += countPairs(l, mid, r)
        return merge(l, mid, r)
    
    mergeSort(0, len(nums) - 1)
    return ans[0]

nums = [1,3,2,3,1]
print(reversePairs(nums))

1 2 3 4 8 12 16 11 10 9 9 5 6 7 11 6 

: 